apiVersion: v1
kind: Service # Type of the object
metadata:
  name: svc-01 # Name of the service
  namespace: ns-01 # Namespace of the service object
spec:
  selector:
    app: tag-01 # To monitor containers with the tag
  ports:
    - protocol: TCP # Protocol type
      port: 80 # Service input port
      targetPort: 80 # Service route port
