apiVersion: v1
kind: Service # Type of the object
metadata:
  name: whoami-svc # Name of the service
  namespace: my-ns # Namespace of the service object
spec:
  selector:
    app: whoami # To monitor containers with the tag
  ports:
    - protocol: TCP # Protocol type
      port: 80 # Service input port
      targetPort: 80 # Service route port